name: Test
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    Node:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: latest
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build
    Bun:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v3
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: Install Dependencies
              run: bun install
            - name: Build
              run: bun run build
    Yarn:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: latest
            - name: Install Dependencies
              run: yarn install
            - name: Build
              run: yarn run build
    PNPM:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: latest
            - name: Install PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Install Dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build
